### ISSUE TITLE
absolute pathes vs relative

### ISSUE THREAD

**Issue by mikebutts** [michalis-tsiropoulos/colmar#2]
https://github.com/michalis-tsiropoulos/colmar/blob/550896921441812d9cb91f895720c743f0fbfac8/index.html#L89-L90

You have some images trying to load from your C drive. Other images are using a relative path to where they are. These should ALL be relative.

![image](https://user-images.githubusercontent.com/8017734/31312486-5136f2ea-ab92-11e7-90da-75f5d500d549.png)
****

**Comment by michalis-tsiropoulos** [comment]
fixed.
