### ISSUE TITLE
Left and right side

### ISSUE THREAD

**Issue by mikebutts** [michalis-tsiropoulos/colmar#3]
https://github.com/michalis-tsiropoulos/colmar/blob/550896921441812d9cb91f895720c743f0fbfac8/index.html#L48-L54

This works for the most part but a better way to do this would be having a main div and 2 divs in it being left 60% and right 40% then the things inside are much easier to manage. This would also allow you to center the right half.

**Comment by michalis-tsiropoulos** [comment]
fixed.
