### ISSUE TITLE
Images distorted

### ISSUE THREAD

**Issue by mikebutts** [michalis-tsiropoulos/colmar#4]
https://github.com/michalis-tsiropoulos/colmar/blob/550896921441812d9cb91f895720c743f0fbfac8/index.html#L66-L98

Looks like the width on the image is causing distortion, take it out and it works fine.

![image](https://user-images.githubusercontent.com/8017734/31312521-a956ee0c-ab93-11e7-8c51-fded90c087ff.png)

**Comment by michalis-tsiropoulos** [comment]
Done.
